write a program that allows you to enter 4 numbers and stores them in a file called "Numbers"
.3
.45
.83
.21

In [2]:
first_number = input("enter the first number")
second_number = input("enter the Second number")
third_number = input("enter the third number")
forth_number = input("enter the forth number")

numbers = open("numbers.txt", 'w')
numbers.write(first_number)
numbers.write("\n")
numbers.write(second_number)
numbers.write("\n")
numbers.write(third_number)
numbers.write("\n")
numbers.write(forth_number)
numbers.write("\n")
numbers.close()


Write a program to ask 
a student for their 
percentage mark and 
convert this to a grade

The conversion will be 
done in a function 
called mark_grade


In [4]:
target_grade = int(input("enter your target grade"))


def mark_grade(grade):
    exam_grade = 70
    if grade > exam_grade:
        print('Your grade is above the exam grade')

    elif grade == exam_grade:
        print('Your grade is equal to the exam grade')

    elif grade < exam_grade:
        print('Your grade is below the exam grade')


mark_grade(target_grade)



Your grade is below the exam grade


1. Create a 1D array of numbers from 0 to 9
2. Create a 3×3 NumPy array of all Boolean value Trues
3. Extract all odd numbers from array of 1-10
4. Replace all odd numbers in an array of 1-10 with the value -1
5. Convert a 1D array to a 2D array with 2 rows
6. Create two arrays a and b, stack these two arrays vertically use the np.dot and
np.sum to calculate totals

In [2]:
import numpy as np
x = np.arange(10)
print("Array from 0 to 9:")
print(x)



Array from 0 to 9:
[0 1 2 3 4 5 6 7 8 9]


In [3]:
bool_arr = np.ones((3, 3), dtype=bool)
print('2D Numpy Array: ')
print(bool_arr)


2D Numpy Array: 
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 6, 7, 8, 9])
a[a % 2 == 1]


array([1, 3, 5, 7, 9])

In [7]:
import numpy as np

a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

odd_values = (a % 2 == 1)
a[odd_values] = -1
print(a)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
import numpy as np
a = np.array([1,  2,  3,  4,  5])
b = np.array([6,  7,  8,  9, 10])

c = np.dot(a, b)
print(c)
sum = np.sum(c)
print(sum)


130
130


In [11]:
import numpy as np
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)
c = np.dot(a, b)
print(c)
sum = np.sum(c)
print(sum)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
1944
